baseURL = 'http://sihaog.github.io/'
languageCode = 'en-us'
title = 'SihaoPedia'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'SihaoGao'               # twitter.com/YOUR_TWITTER_ID
  github = 'sihaog'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'sihao.gao@gmail.com'                 # gravatar email or image url
  name = 'Sihao Gao'
  bio = ''


  # misc
  disableHLJS = false                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
